# Generated by Django 2.2.3 on 2019-07-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='主键')),
                ('x_data', models.CharField(max_length=1000, verbose_name='月份')),
                ('y_data', models.CharField(max_length=1000, verbose_name='数值')),
            ],
            options={
                'verbose_name': '测试数据',
                'verbose_name_plural': '测试数据',
            },
        ),
    ]
